site_name: Demo Project
repo_url: https://github.com/malkab/Across
repo_name: GitHub
site_description: Documentation for project Across
site_author: Juan Pedro Pérez Alcántara - Geographica
remote_branch: gh-pages
remote_name: gh-pages
nav:
- Home: index.md
- Test Page:
  - Another-Page.md
  - Subsection: A-Subsection.md
theme: 
  name: material
